# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sell_buy_item' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sell_buy_item
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'FirebaseAuth'
  pod 'Firebase/Storage'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  target 'sell_buy_itemTests' do
    inherit! :search_paths
    # Pods for testing
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'FirebaseAuth'
  pod 'Firebase/Storage'
  end

  target 'sell_buy_itemUITests' do
    inherit! :search_paths
    # Pods for testing
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'FirebaseAuth'
  pod 'Firebase/Storage'
  end

end
